//! Raw bindings to the OpenEXR fallback shim, generated by `build.rs`.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]

include!(concat!(env!("OUT_DIR"), "/exr_shim_bindings.rs"));
