//! Raw bindings to the OCIO C++ shim, generated by `build.rs` (bindgen over
//! `src/ocio/shim.h`). Only `ocio/mod.rs` touches these.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code
)]

#[cfg(feature = "ocio")]
include!(concat!(env!("OUT_DIR"), "/ocio_shim_bindings.rs"));
