from __future__ import annotations

from dataclasses import dataclass
import os
from pathlib import Path
from typing import Any


@dataclass(frozen=True, slots=True)
class DisplayView:
    """An OCIO display/view pair suitable for presentation in the UI."""

    display: str
    view: str


@dataclass(frozen=True, slots=True)
class OcioShader:
    """GPU shader snippet generated by OCIO for display transforms."""

    shader_text: str
    function_name: str


class OcioManager:
    """Isolates OCIO configuration, display/view enumeration, and shader generation."""

    def __init__(self, resources_dir: Path, custom_config_dir: Path) -> None:
        self._resources_dir = resources_dir
        self._custom_config_dir = custom_config_dir
        self._ocio_module: Any | None = None
        self._config: Any | None = None
        self._display_views: list[DisplayView] = [DisplayView("Raw", "Raw")]
        self._active_view: DisplayView = self._display_views[0]

    @property
    def active_view(self) -> DisplayView:
        """Returns the active display/view transform."""

        return self._active_view

    @property
    def display_views(self) -> list[DisplayView]:
        """Returns available display/view transforms."""

        return list(self._display_views)

    def reload(self) -> None:
        """Reloads OCIO from custom or bundled config, with safe fallback behavior."""

        self._ocio_module = self._import_ocio()
        if self._ocio_module is None:
            self._config = None
            self._display_views = [DisplayView("Raw", "Raw")]
            self._active_view = self._display_views[0]
            return

        config_path = self._resolve_config_path()
        if config_path is not None and config_path.exists():
            try:
                self._config = self._ocio_module.Config.CreateFromFile(str(config_path))
            except Exception:
                self._config = self._create_best_builtin_config()
        else:
            self._config = self._create_best_builtin_config()

        self._display_views = self._enumerate_display_views()
        self._active_view = self._choose_default_view(self._display_views)

    def set_active_view(self, display: str, view: str) -> None:
        """Switches active display/view when a matching pair exists."""

        candidate = DisplayView(display, view)
        if candidate in self._display_views:
            self._active_view = candidate

    def build_gpu_shader(self) -> OcioShader:
        """Builds GLSL shader code for the currently selected OCIO display/view."""

        if self._config is None or self._ocio_module is None:
            return OcioShader(shader_text="", function_name="")

        ocio = self._ocio_module
        gpu_desc = ocio.GpuShaderDesc.CreateShaderDesc()
        gpu_desc.setLanguage(ocio.GPU_LANGUAGE_GLSL_4_0)
        gpu_desc.setFunctionName("ocio_display_transform")

        processor = self._config.getProcessor(
            ocio.ROLE_SCENE_LINEAR,
            self._active_view.display,
            self._active_view.view,
            ocio.TRANSFORM_DIR_FORWARD,
        )
        processor.getDefaultGPUProcessor().extractGpuShaderInfo(gpu_desc)

        return OcioShader(
            shader_text=str(gpu_desc.getShaderText()),
            function_name=str(gpu_desc.getFunctionName()),
        )

    def _resolve_config_path(self) -> Path | None:
        """Finds preferred config path: custom folder first, then bundled config."""

        custom_candidates = sorted(self._custom_config_dir.glob("*.ocio"))
        if custom_candidates:
            return custom_candidates[0]

        bundled = self._resources_dir / "config.ocio"
        if bundled.exists():
            return bundled

        return None

    def _enumerate_display_views(self) -> list[DisplayView]:
        """Lists display/view pairs from current config."""

        assert self._config is not None
        display_views: list[DisplayView] = []

        for display in self._config.getDisplays():
            for view in self._config.getViews(display):
                display_views.append(DisplayView(str(display), str(view)))

        if not display_views:
            display_views.append(DisplayView("Raw", "Raw"))

        return display_views

    @staticmethod
    def _choose_default_view(candidates: list[DisplayView]) -> DisplayView:
        """Selects a modern filmic-like view when available; otherwise first entry."""

        preferred_terms = ("agx", "aces", "filmic")
        for item in candidates:
            combined = f"{item.display} {item.view}".lower()
            if any(term in combined for term in preferred_terms):
                return item
        return candidates[0]

    @staticmethod
    def _import_ocio() -> Any | None:
        """Imports PyOpenColorIO lazily to keep startup and tests resilient."""

        if os.environ.get("IMGVWR_DISABLE_OCIO", "0") == "1":
            return None

        if os.name == "nt" and os.environ.get("IMGVWR_ENABLE_OCIO", "0") != "1":
            return None

        try:
            import PyOpenColorIO as ocio
        except ImportError:
            return None
        return ocio

    def _create_best_builtin_config(self) -> Any:
        """Creates a built-in OCIO config preferring ACES/AGX when available."""

        assert self._ocio_module is not None
        ocio = self._ocio_module

        registry = ocio.BuiltinConfigRegistry()
        selected_name: str | None = None
        for item in registry.getBuiltinConfigs():
            name = str(item[0])
            name_lower = name.lower()
            if "agx" in name_lower or "aces" in name_lower:
                selected_name = name
                break

        if selected_name is not None:
            return ocio.Config.CreateFromBuiltinConfig(selected_name)

        return ocio.Config.CreateRaw()
