from __future__ import annotations

import base64
from dataclasses import dataclass
import json
import os
from pathlib import Path
import subprocess
import sys
from typing import Any


@dataclass(frozen=True, slots=True)
class DisplayView:
    """An OCIO display/view pair suitable for presentation in the UI."""

    display: str
    view: str


@dataclass(frozen=True, slots=True)
class OcioTexture2D:
    """A GPU 2D LUT texture required by an OCIO shader."""

    sampler_name: str
    binding_index: int
    width: int
    height: int
    components: int
    interpolation: str
    values: bytes


@dataclass(frozen=True, slots=True)
class OcioTexture3D:
    """A GPU 3D LUT texture required by an OCIO shader."""

    sampler_name: str
    binding_index: int
    edge_len: int
    components: int
    interpolation: str
    values: bytes


@dataclass(frozen=True, slots=True)
class OcioShader:
    """GPU shader snippet generated by OCIO for display transforms."""

    shader_text: str
    function_name: str
    signature: str = ""
    textures_2d: tuple[OcioTexture2D, ...] = ()
    textures_3d: tuple[OcioTexture3D, ...] = ()


class OcioManager:
    """Isolates OCIO configuration, display/view enumeration, and shader generation."""

    def __init__(self, resources_dir: Path, custom_config_dir: Path) -> None:
        self._resources_dir = resources_dir
        self._custom_config_dir = custom_config_dir
        self._ocio_module: Any | None = None
        self._config: Any | None = None
        self._display_views: list[DisplayView] = [DisplayView("Raw", "Raw")]
        self._active_view: DisplayView = self._display_views[0]

    @property
    def active_view(self) -> DisplayView:
        """Returns the active display/view transform."""

        return self._active_view

    @property
    def display_views(self) -> list[DisplayView]:
        """Returns available display/view transforms."""

        return list(self._display_views)

    def reload(self) -> None:
        """Reloads OCIO from custom or bundled config, with safe fallback behavior."""

        if self._use_subprocess_ocio():
            self._reload_via_subprocess()
            return

        self._ocio_module = self._import_ocio()
        if self._ocio_module is None:
            self._config = None
            self._display_views = [DisplayView("Raw", "Raw")]
            self._active_view = self._display_views[0]
            return

        config_path = self._resolve_config_path()
        if config_path is not None and config_path.exists():
            try:
                self._config = self._ocio_module.Config.CreateFromFile(str(config_path))
            except Exception:
                self._config = self._create_best_builtin_config()
        else:
            self._config = self._create_best_builtin_config()

        self._display_views = self._enumerate_display_views()
        self._active_view = self._choose_default_view(self._display_views)

    def set_active_view(self, display: str, view: str) -> None:
        """Switches active display/view when a matching pair exists."""

        candidate = DisplayView(display, view)
        if candidate in self._display_views:
            self._active_view = candidate

    def build_gpu_shader(self) -> OcioShader:
        """Builds GLSL shader code for the currently selected OCIO display/view."""

        if self._use_subprocess_ocio():
            return self._build_gpu_shader_via_subprocess()

        if self._config is None or self._ocio_module is None:
            return OcioShader(shader_text="", function_name="")

        ocio = self._ocio_module
        gpu_desc = ocio.GpuShaderDesc.CreateShaderDesc()
        gpu_desc.setLanguage(ocio.GPU_LANGUAGE_GLSL_4_0)
        gpu_desc.setFunctionName("ocio_display_transform")
        gpu_desc.setAllowTexture1D(False)

        processor = self._config.getProcessor(
            ocio.ROLE_SCENE_LINEAR,
            self._active_view.display,
            self._active_view.view,
            ocio.TRANSFORM_DIR_FORWARD,
        )
        processor.getDefaultGPUProcessor().extractGpuShaderInfo(gpu_desc)

        return OcioShader(
            shader_text=str(gpu_desc.getShaderText()),
            function_name=str(gpu_desc.getFunctionName()),
            signature=f"{self._active_view.display}/{self._active_view.view}",
            textures_2d=self._collect_2d_textures(gpu_desc),
            textures_3d=self._collect_3d_textures(gpu_desc),
        )

    def _reload_via_subprocess(self) -> None:
        """Reloads display/view list via a helper subprocess to avoid in-process OCIO import."""

        config_path = self._resolve_config_path()
        command = [
            sys.executable,
            "-m",
            "hdri_viewer.color.ocio_subprocess",
            "enumerate",
            "--config",
            str(config_path) if config_path is not None else "",
        ]

        try:
            completed = subprocess.run(
                command,
                check=False,
                capture_output=True,
                text=True,
            )
        except Exception:
            completed = None

        if completed is None or completed.returncode != 0:
            self._ocio_module = None
            self._config = None
            self._display_views = [DisplayView("Raw", "Raw")]
            self._active_view = self._display_views[0]
            return

        try:
            payload = json.loads(completed.stdout)
            raw_pairs = payload.get("display_views", [])
            display_views = [DisplayView(str(pair[0]), str(pair[1])) for pair in raw_pairs if len(pair) == 2]
        except Exception:
            display_views = []

        if not display_views:
            display_views = [DisplayView("Raw", "Raw")]

        self._ocio_module = None
        self._config = None
        self._display_views = display_views
        self._active_view = self._choose_default_view(self._display_views)

    def _build_gpu_shader_via_subprocess(self) -> OcioShader:
        """Builds OCIO GLSL via helper subprocess."""

        config_path = self._resolve_config_path()
        command = [
            sys.executable,
            "-m",
            "hdri_viewer.color.ocio_subprocess",
            "shader",
            "--config",
            str(config_path) if config_path is not None else "",
            "--display",
            self._active_view.display,
            "--view",
            self._active_view.view,
        ]

        try:
            completed = subprocess.run(
                command,
                check=False,
                capture_output=True,
                text=True,
            )
        except Exception:
            return OcioShader(shader_text="", function_name="")

        if completed.returncode != 0:
            return OcioShader(shader_text="", function_name="")

        try:
            payload = json.loads(completed.stdout)
        except Exception:
            return OcioShader(shader_text="", function_name="")

        texture_2d_items: list[OcioTexture2D] = []
        for item in payload.get("textures_2d", []):
            values_b64 = str(item.get("values_b64", ""))
            if not values_b64:
                continue
            channel_text = str(item.get("channel", ""))
            components = 4
            if "RED" in channel_text:
                components = 1
            elif "RGB" in channel_text:
                components = 3

            try:
                values = base64.b64decode(values_b64)
            except Exception:
                continue

            texture_2d_items.append(
                OcioTexture2D(
                    sampler_name=str(item.get("sampler_name", "")),
                    binding_index=int(item.get("binding_index", 0)),
                    width=int(item.get("width", 1)),
                    height=int(item.get("height", 1)),
                    components=components,
                    interpolation=str(item.get("interpolation", "")),
                    values=values,
                )
            )

        texture_3d_items: list[OcioTexture3D] = []
        for item in payload.get("textures_3d", []):
            values_b64 = str(item.get("values_b64", ""))
            if not values_b64:
                continue
            try:
                values = base64.b64decode(values_b64)
            except Exception:
                continue

            edge_len = int(item.get("edge_len", 2))
            total_pixels = max(edge_len * edge_len * edge_len, 1)
            float_count = len(values) // 4
            components = max(1, min(4, float_count // total_pixels))

            texture_3d_items.append(
                OcioTexture3D(
                    sampler_name=str(item.get("sampler_name", "")),
                    binding_index=int(item.get("binding_index", 0)),
                    edge_len=edge_len,
                    components=components,
                    interpolation=str(item.get("interpolation", "")),
                    values=values,
                )
            )

        return OcioShader(
            shader_text=str(payload.get("shader_text", "")),
            function_name=str(payload.get("function_name", "")),
            signature=str(payload.get("signature", "")),
            textures_2d=tuple(texture_2d_items),
            textures_3d=tuple(texture_3d_items),
        )

    def _resolve_config_path(self) -> Path | None:
        """Finds preferred config path: custom folder first, then bundled config."""

        custom_candidates = sorted(self._custom_config_dir.glob("*.ocio"))
        if custom_candidates:
            return custom_candidates[0]

        bundled = self._resources_dir / "config.ocio"
        if bundled.exists():
            return bundled

        return None

    @staticmethod
    def _use_subprocess_ocio() -> bool:
        """Returns whether OCIO operations should run in a subprocess helper."""

        default_value = "1" if os.name == "nt" else "0"
        return os.environ.get("IMGVWR_USE_SUBPROCESS_OCIO", default_value) == "1"

    def _enumerate_display_views(self) -> list[DisplayView]:
        """Lists display/view pairs from current config."""

        assert self._config is not None
        display_views: list[DisplayView] = []

        for display in self._config.getDisplays():
            for view in self._config.getViews(display):
                display_views.append(DisplayView(str(display), str(view)))

        if not display_views:
            display_views.append(DisplayView("Raw", "Raw"))

        return display_views

    @staticmethod
    def _choose_default_view(candidates: list[DisplayView]) -> DisplayView:
        """Prefers Standard/sRGB when available; otherwise uses sensible fallback."""

        for item in candidates:
            if item.display.lower() == "srgb" and item.view.lower() == "standard":
                return item

        for item in candidates:
            if item.view.lower() == "standard":
                return item

        for item in candidates:
            if item.display.lower() == "srgb":
                return item

        return candidates[0]

    @staticmethod
    def _import_ocio() -> Any | None:
        """Imports PyOpenColorIO lazily to keep startup and tests resilient."""

        if os.environ.get("IMGVWR_DISABLE_OCIO", "0") == "1":
            return None

        try:
            import PyOpenColorIO as ocio
        except ImportError:
            return None
        return ocio

    def _create_best_builtin_config(self) -> Any:
        """Creates a built-in OCIO config preferring ACES/AGX when available."""

        assert self._ocio_module is not None
        ocio = self._ocio_module

        registry = ocio.BuiltinConfigRegistry()
        selected_name: str | None = None
        for item in registry.getBuiltinConfigs():
            name = str(item[0])
            name_lower = name.lower()
            if "agx" in name_lower or "aces" in name_lower:
                selected_name = name
                break

        if selected_name is not None:
            return ocio.Config.CreateFromBuiltinConfig(selected_name)

        return ocio.Config.CreateRaw()

    @staticmethod
    def _collect_2d_textures(gpu_desc: Any) -> tuple[OcioTexture2D, ...]:
        """Extracts OCIO 2D LUT texture payloads from shader descriptor."""

        textures: list[OcioTexture2D] = []
        for texture in gpu_desc.getTextures():
            channel_text = str(texture.channel)
            components = 4
            if "RED" in channel_text:
                components = 1
            elif "RGB" in channel_text:
                components = 3

            values = texture.getValues().astype("float32", copy=False).tobytes()
            textures.append(
                OcioTexture2D(
                    sampler_name=str(texture.samplerName),
                    binding_index=int(texture.textureShaderBindingIndex),
                    width=int(texture.width),
                    height=int(texture.height),
                    components=components,
                    interpolation=str(texture.interpolation),
                    values=values,
                )
            )
        return tuple(textures)

    @staticmethod
    def _collect_3d_textures(gpu_desc: Any) -> tuple[OcioTexture3D, ...]:
        """Extracts OCIO 3D LUT texture payloads from shader descriptor."""

        textures: list[OcioTexture3D] = []
        for texture in gpu_desc.get3DTextures():
            values_array = texture.getValues().astype("float32", copy=False)
            edge_len = int(texture.edgeLen)
            total_pixels = max(edge_len * edge_len * edge_len, 1)
            components = max(1, min(4, int(values_array.size // total_pixels)))
            textures.append(
                OcioTexture3D(
                    sampler_name=str(texture.samplerName),
                    binding_index=int(texture.textureShaderBindingIndex),
                    edge_len=edge_len,
                    components=components,
                    interpolation=str(texture.interpolation),
                    values=values_array.tobytes(),
                )
            )
        return tuple(textures)
